[package]
name = "genzlang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chumsky = { version = "1.0.0-alpha.6" }

[dev-dependencies]
pretty_assertions = "1.4.0"
